# Usar una imagen base de OpenJDK
FROM openjdk:21-jdk-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR de la aplicación al contenedor
COPY target/AlmacenInfinitoDeRecursosBackEnd-0.0.1-SNAPSHOT.jar AlmacenInfinitoDeRecursosBackEnd.jar

 # Copia las plantillas de Thymeleaf
COPY src/main/resources/Templates/ app/resources/Templates/

# Exponer el puerto en el que correrá la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "AlmacenInfinitoDeRecursosBackEnd.jar"]
